### ISSUE TITLE
Support linux-arm64-musl

### ISSUE THREAD

**Issue by jylin** [libsql/libsql-client-ts#118]
I get an error `error: Cannot find module "@libsql/linux-arm64-musl"`, but that doesn't seem to be a package that exists?

Using Bun and aarch64 GNU/Linux.

**Comment by penberg** [comment]
Hey @jylin! We likely just need the following workaround for Bun on arm too: https://github.com/libsql/libsql-js/commit/39c8ac802093282718459140ab3562baf91f183c

I added the following to `libsql` (the package this client uses internally): https://github.com/libsql/libsql-js/commit/f93b4df9bd951ab01828ebfe1c39a285c575a655 and released 0.1.32. Let me know if you're able to test it to verify it fixes the problem for you and I will bump the dependency in this repository.

**Comment by jylin** [comment]
I just tested that patch and it does fix my issue, thanks!
