### ISSUE TITLE
WebSocket connection breakage with Vercel Edge functions

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-client-ts#23]
Numnumberry writes on Turso Discord that the following code on Vercel:

![image](https://user-images.githubusercontent.com/81939/233832052-f9ba0c92-1331-448f-98b6-6d8225a27900.png)

Fails as follows:

![image](https://user-images.githubusercontent.com/81939/233832056-2daecc85-69b6-41e1-a9ea-079f099d00ff.png)

Looks like a bug in https://github.com/libsql/isomorphic-ts, but since it triggers via the TypeScript client API, let's track it here.

**Comment by honzasp** [comment]
Vercel edge functions don't support WebSockets, #25 at least fixes the error message.
