### ISSUE TITLE
Can't resolve 'utf-8-validation' on Windows

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-client-ts#33]
Someone on Drizzle Discord reported the following error:

https://cdn.discordapp.com/attachments/1103436143875334244/1103436144026325072/image.png

The workaround the reported gave was:

https://github.com/netlify/netlify-lambda/issues/179#issuecomment-1450473343

Let's see if we can fix this in our packaging directly.

**Comment by honzasp** [comment]
Hmm, this seems to be an issue that originates in the build process of Netlify Functions that involves 3rd party libraries, it's not clear to me how we could fix that issue? The comment by irzko in the linked issue is just a snippet of unformatted code without any explanation (it seems to be a config file for Next.js, perhaps?).

**Comment by honzasp** [comment]
Closing for now. Feel free to reopen if we hit this issue again and have more information.
