### ISSUE TITLE
Library in serverless environment is bloated by better-sqlite3

### ISSUE THREAD

**Issue by khuezy** [libsql/libsql-client-ts#60]
Hi, I'm deploying an app on AWS Lambda and using esbuild to bundle the handler. Since `better-sqlite3` depends on a binary, it has to be excluded from the bundle. In a non-local environment, I want to omit any dependency of this dependency and use the ws/https scheme instead. The problem is that the `createClient` api imports the "sqlite3" file at the top: https://github.com/libsql/libsql-client-ts/blob/main/src/index.ts#L5

I could install `better-sqlite3` on the lambda, but that bloats the lambda from ~400kb to ~9MB (compressed). My work around was patching `@libsql/client` and removing the `sqlite3` import from the top of the file and dynamically importing in the final `else` block. I had to make `createClient` an async function though.

Any thoughts/recommendations?

**Comment by CodingDoug** [comment]
If you import like this:

```ts
import { createClient } from "@libsql/client/web";
```

That should avoid importing from sqlite3 and just provide a client that supports http and ws (this is the whole reason why this import variant exists). However, that won't stop npm from installing better-sqlite3 when you install libsql-client. But you should be able to remove it from node_modules, if that's all you need.

**Comment by khuezy** [comment]
Thanks @CodingDoug ! If I change the import to the `/web` variant, then my local environment breaks b/c it's missing the local sqlite3 dependency.

**Comment by CodingDoug** [comment]
Right, you unfortunately can't have it both ways. This is something that we haven't found to be solvable from a SDK build perspective.

Maybe you can conditionally and dynamically import based the variant you want, based on the environment, in order to avoid importing better-sqlite3 when you can't use it.

**Comment by khuezy** [comment]
Yeah that's what I ended up doing. Thanks!
