### ISSUE TITLE
The switch to libsql package inherits libsql semicolon parsing problems via executeMultiple()

### ISSUE THREAD

**Issue by CodingDoug** [libsql/libsql-client-ts#81]
After better-sqlite3 was replaced with libsql, `client.executeMultiple()` when used with a local db file now fails with semicolon parsing issues as described in https://github.com/libsql/libsql-js/issues/31

**Comment by penberg** [comment]
Fixed by https://github.com/libsql/libsql-client-ts/commit/a097ebfee3e005a168aecec20dc2151f4a3886ca
