### ISSUE TITLE
Vercel Serverless Cannot find module '@libsql/linux-x64-gnu'

### ISSUE THREAD

**Issue by diboune** [libsql/libsql-client-ts#84]
After upgrading to @libsql/client@0.3.3-pre.2 it started giving me this error in the Vercel logs --- @libsql/client@0.3.2 works fine.

```Cannot find module '@libsql/linux-x64-gnu'
Require stack:
- /var/task/node_modules/.pnpm/libsql@0.1.4/node_modules/libsql/index.js
- /var/task/node_modules/.pnpm/@libsql+client@0.3.3-pre.2/node_modules/@libsql/client/lib-cjs/sqlite3.js
- /var/task/node_modules/.pnpm/@libsql+client@0.3.3-pre.2/node_modules/@libsql/client/lib-cjs/node.js
- /var/task/node_modules/.pnpm/drizzle-orm@0.28.6_@libsql+client@0.3.3-pre.2/node_modules/drizzle-orm/libsql/index.cjs
- /var/task/apps/web/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js
Did you forget to add it to "dependencies" in `package.json`?
RequestId: 963e7577-fe2b-41be-80c8-e666c3c91b23 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by penberg** [comment]
@diboune can you please test 0.3.5-pre.2 with the following additional configuration:

https://github.com/libsql/libsql-client-ts#using-the-library-with-nextjs

The extra config is not needed if you use a version of Next with https://github.com/vercel/next.js/pull/55266 included.

**Comment by penberg** [comment]
Thanks for reporting back, @diboune!

**Comment by hamedmam** [comment]
I just faced this issue with Lambda on AWS, any fix that's not specific to Vercel @penberg ?

**Comment by hugotox** [comment]
Hello! I'm having the same issue trying to build a sveltekit app on vercel. 
I can't pass the build step, it fails with `Error: Cannot find module '@libsql/linux-x64-gnu'`
I'm using `"@libsql/client": "^0.3.5"`. Any advice?
